version: '3'
services:
  elmarket-backend:
    build: ./backend
    image: movlera/elmarket:backend4.0
    depends_on:
      - mongodb
    restart: always
    volumes:
      - public_images:/src/app/public
    environment:
      DB_HOST: mongodb

  elmarket-frontend:
    build:
      context: ./frontend
      args:
        api_url: "/api"
    image: movlera/elmarket:frontend9.0
    depends_on:
      - elmarket-backend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  mongodb:
    image: mongo:4.4.18
    restart: on-failure
    volumes:
      - mongo_data:/data/db

volumes:
  public_images:
  mongo_data: